name: Docker Deploy

on:
  workflow_run:
    workflows: ["CMake"]
    branches: [master]
    types: 
      - completed

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} 
           -p ${{ secrets.DOCKER_PASS }}
    - name: Build Docker image
      run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
    - name: Publish Docker image
      run: docker push $REPO
